# Zomato Análise Espacial
 //zomato spacial analysis

In [1]:
#importando bibliotecas para análise espacial
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly as plot
import seaborn as sns
from geopy.geocoders import Nominatim
import folium
from folium.plugins import HeatMap
from folium.plugins import FastMarkerCluster
import kagglehub

c:\Users\Caroline\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#importando arquivos
#importing files

#urls
urls = ['https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part0.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part1.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part10.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part2.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part3.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part4.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part5.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part6.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part7.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part8.csv',
        'https://raw.githubusercontent.com/CarolineMNves/Zomato_an-lise_espacial/refs/heads/main/files/zomato_part9.csv']

#reading // lendo
df_zomato = pd.concat([pd.read_csv(url) for url in urls])
print(type(df_zomato))
print('==*=='*27)
print(df_zomato.head(3))
print('==*=='*27)
print(df_zomato.tail())

<class 'pandas.core.frame.DataFrame'>
==*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*==
                                                 url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...
1  https://www.zomato.com/bangalore/spice-elephan...
2  https://www.zomato.com/SanchurroBangalore?cont...

                                             address             name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...            Jalsa
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...   Spice Elephant
2  1112, Next to KIMS Medical College, 17th Cross...  San Churro Cafe

  online_order book_table   rate  votes                           phone  \
0          Yes        Yes  4.1/5    775  080 42297555\r\n+91 9743772233
1          Yes         No  4.1/5    787                    080 41714161
2          Yes         No  3.8/5    918                  +91 9663487993

       location            rest_type  \
0  Banashankari        Casual Dining
1  Banashankari        Casual Dining
2  Banashankari  Cafe, Casual Dining

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                         800
1     Chinese, North Indian, Thai                         800
2          Cafe, Mexican, Italian                         800

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []

  listed_in(type) listed_in(city)
0          Buffet    Banashankari
1          Buffet    Banashankari
2          Buffet    Banashankari
==*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*==
                                                    url  \
4995  https://www.zomato.com/bangalore/telugu-velugu...
4996  https://www.zomato.com/bangalore/gowdaaa-mane-...
4997  https://www.zomato.com/bangalore/harvest-marke...
4998  https://www.zomato.com/bangalore/palkis-bellan...
4999  https://www.zomato.com/bangalore/al-khwaja-bel...

                                                address               name  \
4995  Food Court, Building 8, Pritech Park, Adarsh P...      Telugu Velugu
4996  77/1, Marathalli Outer Ring Road, Bellandur, B...  Gowdaaa Mane Oota
4997  The Bay, Building 8A and 8B, RMZ Ecoworld, Dod...     Harvest Market
4998                                 2, Outer Ring Road            Palki's
4999     56, Srinivas Reddy Building, Devarabisanahalli          Al Khwaja

     online_order book_table    rate  votes                           phone  \
4995           No         No  3.0 /5      6  +91 7899051624\n00 08022584000
4996           No         No  3.4 /5      7                  +91 9980840421
4997           No         No  3.6 /5     19                  +91 9885576726
4998           No         No  3.0 /5    155    080 25747067\n+91 7760349362
4999           No         No  3.0 /5     13                  +91 9741622367

       location      rest_type  \
4995  Bellandur     Food Court
4996  Bellandur    Quick Bites
4997  Bellandur     Food Court
4998  Bellandur  Casual Dining
4999  Bellandur    Quick Bites

                                             dish_liked  \
4995                                                NaN
4996                                                NaN
4997                                                NaN
4998  Outdoor Sitting Arrangement, Vegetable Biryani...
4999                                                NaN

                   cuisines approx_cost(for two people)  \
4995  South Indian, Biryani                         300
4996           South Indian                         200
4997     Continental, Pizza                         500
4998  North Indian, Biryani                         800
4999  North Indian, Chinese                         400

                                           reviews_list menu_item  \
4995  [('Rated 1.0', "RATED\n  Last Friday we went t...        []
4996  [('Rated 5.0', 'RATED\n  Purely Mandaya Style ...        []
4997  [('Rated 5.0', "RATED\n  Harvest Market is eas...        []
4998  [('Rated 3.0', 'RATED\n  Ordered a lot of veg ...        []
4999  [('Rated 5.0', 'RATED\n  Brilliant budget frie...        []

     listed_in(type) listed_in(city)
4995        Dine-out   Sarjapur Road
4996        Dine-out   Sarjapur Road
4997        Dine-out   Sarjapur Road
4998        Dine-out   Sarjapur Road
4999        Dine-out   Sarjapur Road

In [3]:
print(df_zomato.info())
print('==*=='*27)
print(df_zomato.duplicated().sum())
print('==*=='*27)
print(df_zomato.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 51717 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 7.1+ MB
None
==*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*==
0
==*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*==
url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

Como o objetivo será a análise e, posteriormente, implementação de técnica de ML, todas as linhas com entradas nulas para
as colunas 'rate', 'location' e 'rest_type' que possuem informações de nota, localização e tipo de restaurante, respectivamente, serão removidas.

In [4]:
df_zomato.dropna(subset= ['rate','location','rest_type'], inplace= True)
print(df_zomato.isna().sum())

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                               0
votes                              0
phone                            828
location                           0
rest_type                          0
dish_liked                     20252
cuisines                          11
approx_cost(for two people)      250
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

#### Tratamento

In [5]:
zomato2 = df_zomato.copy()
zomato2['location'] = zomato2['location'] + ', Bangalore, Karnataka, India'
zomato2['location']

0       Banashankari, Bangalore, Karnataka, India
1       Banashankari, Bangalore, Karnataka, India
2       Banashankari, Bangalore, Karnataka, India
3       Banashankari, Bangalore, Karnataka, India
4       Basavanagudi, Bangalore, Karnataka, India
                          ...
4995       Bellandur, Bangalore, Karnataka, India
4996       Bellandur, Bangalore, Karnataka, India
4997       Bellandur, Bangalore, Karnataka, India
4998       Bellandur, Bangalore, Karnataka, India
4999       Bellandur, Bangalore, Karnataka, India
Name: location, Length: 43791, dtype: object

extraindo coordenadas de lat e long de atributos com nome e linhas de endereço

In [6]:
lat_long = pd.DataFrame()
lat_long['Name'] = zomato2['location'].unique()
lat_long.head()

                                              Name
0        Banashankari, Bangalore, Karnataka, India
1        Basavanagudi, Bangalore, Karnataka, India
2         Mysore Road, Bangalore, Karnataka, India
3           Jayanagar, Bangalore, Karnataka, India
4  Kumaraswamy Layout, Bangalore, Karnataka, India

In [7]:
geolocator = Nominatim(user_agent= 'app', timeout= None)

lat = []
lon= []

for name in lat_long['Name']:
  location= geolocator.geocode(name)

  if location is None:
    lat.append(np.nan)
    lon.append(np.nan)
  else:
    lat.append(location.latitude)
    lon.append(location.longitude)

print(f'Latidudes encontradas: {lat}')
print('=*='*22)
print(f'Longitudes encontradas: {lon}')

Latidudes encontradas: [12.9393328, 12.9417261, 12.953668791187688, 12.9399039, 12.9067683, 12.9274413, 12.9660722, 12.9055682, 12.9096941, 12.864107149999999, 12.965717999999999, 12.951855665820787, 12.9163603, 12.93909799796322, 12.9089453, 12.9854892, 12.848759900000001, 12.9489339, 12.9575547, 12.9348429, 12.970018575089048, 12.90056335, 12.9552572, 12.9364846, 12.92535245, 12.924013794074499, 12.9696365, 12.9739905, 12.9606321, 12.9962979, 12.9277245, 12.9986827, 12.9755264, 12.97364413065367, 12.972228669472916, 12.975700066194872, 12.9778793, 12.96668780296818, 12.986391, 12.980005949674641, 12.975801449285402, 12.985725778251844, 12.983009663675498, 12.982242260731894, 12.9934283, 12.9624669, 12.9408685, 12.9467081, 12.9678074, 12.982970719351052, 12.9931876, 13.0093455, 12.9390255, 12.9779079, 12.957998, 12.97339325, 12.9578658, 12.96381425, 12.9876393, 12.9592202, 12.9243692, 12.9282918, 12.9327778, 12.947945899082507, 12.958817250351021, 13.0005359, 13.007516, 13.0227204, 13.0058357, 13.0439323, 13.0422794, 13.037077, 13.0221416, 13.0358698, nan, 12.973936, 12.9846713, 13.0382184, 12.9176571, 13.039409299999999, 12.98780640998248, 13.0027353, nan, 12.99118045, 13.02383, 13.0096524, 12.975608, 13.10850545, 13.0621474, 13.0394104, 12.9819569258295, 13.0330515]
=*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*=
Longitudes encontradas: [77.5539819, 77.5755021, 77.54250544073724, 77.5826382, 77.5595021, 77.5155224, 77.6125940647638, 77.5455438, 77.5866067, 77.55441638924378, 77.5762705372058, 77.60401135701308, 77.604733, 77.57533159964348, 77.6239038, 77.6679809, 77.64825295827616, 77.5968273, 77.5979099, 77.6189768, 77.61701974132181, 77.64947470503677, 77.6984163, 77.6134783, 77.6759410570909, 77.6530859615482, 77.7497448, 77.61449005854067, 77.64249975, 77.5452778, 77.6327822, 77.615525, 77.6067902, 77.60750847201824, 77.59866613619609, 77.60208311450552, 77.6246697, 77.59874713313619, 77.6075416, 77.60500064990403, 77.60169240479877, 77.59604055863997, 77.57678789965348, 77.60826495277115, 77.5902145, 77.6381958, 77.617338, 77.6286805, 77.6568367, 77.63746119817631, 77.5753419, 77.6377094, 77.6238477, 77.5723936, 77.6037312, 77.61124684880099, 77.6958748, 77.72243691580387, 77.7377718, 77.7462921, 77.6242433, 77.6254034, 77.6294052, 77.64073420117386, 77.60615516864692, 77.5496996, 77.695935, 77.595715, 77.6281321, 77.6254268017299, 77.6248577, 77.6413572, 77.6403368, 77.6323597, nan, 77.6509982, 77.6790908, 77.5919, 77.4837568, 77.564092, 77.58739262406627, 77.5703253, nan, 77.54489175084052, 77.5529215, 77.5530535343493, 77.5553564, 77.58533304149645, 77.58006135480495, 77.5197351, 77.51837412776779, 77.5332233]

In [8]:
lat_long['lat'] = lat
lat_long['lon'] = lon
lat_long.isnull().sum()

Name    0
lat     2
lon     2
dtype: int64

In [11]:
lat_long[lat_long['lat'].isnull()]

                                            Name  lat  lon
74  Rammurthy Nagar, Bangalore, Karnataka, India  NaN  NaN
82   Sadashiv Nagar, Bangalore, Karnataka, India  NaN  NaN

In [12]:
lat_long['lat'][79] = 13.0120218
lat_long['lon'][79] = 77.6777817

lat_long['lat'][85] = 13.010316
lat_long['lon'][85] = 77.580569

C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  lat_long['lat'][79] = 13.0120218
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_long['lat'][79] = 13.0120218
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  lat_long['lon'][79] = 77.6777817
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_long['lon'][79] = 77.6777817
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  lat_long['lat'][85] = 13.010316
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_long['lat'][85] = 13.010316
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  lat_long['lon'][85] = 77.580569
C:\Users\Caroline\AppData\Local\Temp\ipykernel_7988\4126681018.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_long['lon'][85] = 77.580569

In [13]:
a = lat_long['lat'][79]
b= lat_long['lon'][79] 
d= lat_long['lat'][85] 
e=lat_long['lon'][85]

print(f'{a}, {b} \n {d}, {e}')

13.0120218, 77.6777817
 13.010316, 77.580569